lint.select = [
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "PLC",# pylint
    "PLE",# pylint
    "PLR",# pylint
    "PLW",# pylint
    "Q",  # flake8-quotes
    "RUF",# Ruff-specific rules
    "S",  # flake8-bandit
    "T",  # flake8-tidy-imports
    "UP", # pyupgrade
    "C",  # McCabe complexity
]
lint.ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the first line
    "D401", # First line should be in imperative mood
]
[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 4

[lint.pylint]
max-args = 4
max-locals = 15   # Set the limit for the number of local variables
max-returns = 6   # Set the limit for the number of return statements
max-statements = 10  # Set the limit for the number of statements
max-public-methods = 20  # Set the limit for the number of public methods in a class